import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { satoshi } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="hydrated">
      <body className={`${satoshi.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
